#### Support Vector Regressor (SVR)


In [2]:
#Importing the libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, VotingRegressor, AdaBoostRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.svm import SVR
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import os
%matplotlib inline

In [1]:
cd D:\Web\AI Huawei Course\Material\Day7

d:\Web\AI Huawei Course\Material\Day7


In [3]:
#Get the dataset
df = pd.read_csv("Advertising_data.csv")
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   2210
1   44.5   39.3       45.1   1040
2   17.2   45.9       69.3    930
3  151.5   41.3       58.5   1850
4  180.8   10.8       58.4   1290

In [5]:
df.shape

(200, 4)

In [6]:
df.describe()

TV       radio   newspaper        sales
count  200.000000  200.000000  200.000000   200.000000
mean   147.042500   23.264000   30.554000  1402.250000
std     85.854236   14.846809   21.778621   521.745657
min      0.700000    0.000000    0.300000   160.000000
25%     74.375000    9.975000   12.750000  1037.500000
50%    149.750000   22.900000   25.750000  1290.000000
75%    218.825000   36.525000   45.100000  1740.000000
max    296.400000   49.600000  114.000000  2700.000000

In [7]:
#Get the regression variables
X = df.drop(['sales'], axis=1)
y = df['sales'].values.reshape(-1,1)

In [8]:
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [9]:
y

array([[2210],
       [1040],
       [ 930],
       [1850],
       [1290],
       [ 720],
       [1180],
       [1320],
       [ 480],
       [1060],
       [ 860],
       [1740],
       [ 920],
       [ 970],
       [1900],
       [2240],
       [1250],
       [2440],
       [1130],
       [1460],
       [1800],
       [1250],
       [ 560],
       [1550],
       [ 970],
       [1200],
       [1500],
       [1590],
       [1890],
       [1050],
       [2140],
       [1190],
       [ 960],
       [1740],
       [ 950],
       [1280],
       [2540],
       [1470],
       [1010],
       [2150],
       [1660],
       [1710],
       [2070],
       [1290],
       [ 850],
       [1490],
       [1060],
       [2320],
       [1480],
       [ 970],
       [1140],
       [1070],
       [2260],
       [2120],
       [2020],
       [2370],
       [ 550],
       [1320],
       [2380],
       [1840],
       [ 810],
       [2420],
       [1570],
       [1400],
       [1800],
       [ 930],
       [ 9

In [10]:
#Splitting our dataset to Training and Testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [50]:
#Linear SVR
svrlin = SVR(kernel='linear')
svrlin.fit(X_train, y_train)

C:\Users\Dr-ahmed\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(kernel='linear')

In [51]:
# predicting the Test set result
y_pred = svrlin.predict(X_test)

###### Get The Equation parameters ( cofficient and intercept)

In [13]:
#Calculating the Coefficients (3 Coefficients )
svr.coef_

array([[ 4.33808371e+00,  1.97827244e+01, -1.74801013e-02]])

In [14]:
#Calculating the Intercept
svr.intercept_

array([333.79758633])

###### Get the Regression Metrics ( r2, MAE, MSE)

In [18]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.8911575775703482

In [19]:
#Calculating the MAE Error
mean_absolute_error(y_test, y_pred)

142.57228183425818

In [20]:
#Calculating the MSE Error
mean_squared_error(y_test, y_pred)

34354.58004335417

In [22]:
#Poly SVR
svr = SVR(kernel='poly', degree=2)
svr.fit(X_train, y_train)

C:\Users\Dr-ahmed\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(degree=2, kernel='poly')

In [23]:
# predicting the Test set result
y_pred = svr.predict(X_test)

In [24]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.3439979282704193

In [25]:
#Calculating the MAE Error
mean_absolute_error(y_test, y_pred)

368.7180634348068

In [26]:
#Calculating the MSE Error
mean_squared_error(y_test, y_pred)

207057.82891230847

In [27]:
#RBF SVR
svr = SVR(kernel='rbf')
svr.fit(X_train, y_train)

C:\Users\Dr-ahmed\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [28]:
# predicting the Test set result
y_pred = svr.predict(X_test)

In [30]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.06554745169430642

#### KNN Regressor

In [31]:
knnreg=KNeighborsRegressor()
knnreg.fit(X_train, y_train)
y_pred= knnreg.predict(X_test)

In [32]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.9106204438460054

In [33]:
#Calculating the MAE Error
mean_absolute_error(y_test, y_pred)

118.9

In [34]:
#Calculating the MSE Error
mean_squared_error(y_test, y_pred)

28211.4

#### Decision Tree Regressor

In [35]:
dtreg=DecisionTreeRegressor()
dtreg.fit(X_train, y_train)
y_pred= dtreg.predict(X_test)

In [36]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.927495581836273

In [37]:
#Calculating the MAE Error
mean_absolute_error(y_test, y_pred)

105.0

In [38]:
#Calculating the MSE Error
mean_squared_error(y_test, y_pred)

22885.0

#### Naieve Bayes Regressor

In [39]:
nbreg= GaussianNB()
nbreg.fit(X_train, y_train)
y_pred=nbreg.predict(X_test)

C:\Users\Dr-ahmed\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [41]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.804276089442445

In [42]:
#Calculating the MAE Error
mean_absolute_error(y_test, y_pred)

192.75

In [43]:
#Calculating the MSE Error
mean_squared_error(y_test, y_pred)

61777.5

### Ensemble Model

In [52]:
vr=VotingRegressor( [('SVR', svr), ('knnreg', knnreg) ,  ('dtreg', dtreg)] )

In [53]:
vr.fit(X_train, y_train)
y_pred= vr.predict(X_test)

C:\Users\Dr-ahmed\anaconda3\Lib\site-packages\sklearn\ensemble\_voting.py:694: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [55]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.8531745390450409

#### Random Forest Regressor

In [56]:
rereg= RandomForestRegressor()
rereg.fit(X_train, y_train)
y_pred=rereg.predict(X_test)

C:\Users\Dr-ahmed\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [57]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.9833163183454039

In [58]:
#Calculating the MAE Error
mean_absolute_error(y_test, y_pred)

60.35999999999999

In [59]:
#Calculating the MSE Error
mean_squared_error(y_test, y_pred)

5265.969499999998

#### Adaboost Regressor

In [62]:
adareg=AdaBoostRegressor()
adareg.fit(X_train, y_train)
y_pred= adareg.predict(X_test)

C:\Users\Dr-ahmed\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [63]:
#Calculating the R squared value
r2_score(y_test, y_pred)

0.9669496880404551

In [64]:
#Calculating the MAE Error
mean_absolute_error(y_test, y_pred)

87.38531769097652

In [65]:
#Calculating the MSE Error
mean_squared_error(y_test, y_pred)

10431.866200018403

In [68]:
xgb=XGBRegressor()
xgb.fit(X_train, y_train)
y_pred= xgb.predict(X_test)
#Calculating the R squared value
r2_score(y_test, y_pred)

0.972496509552002