### Breast Cancer Classification using many classifiers

In [1]:
import pip
pip.main(['install', 'scikit-learn'])


Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


Requirement already satisfied: scikit-learn in c:\users\lenovo\anaconda3\envs\karim-new\lib\site-packages (1.5.2)

Requirement already satisfied: numpy>=1.19.5 in c:\users\lenovo\anaconda3\envs\karim-new\lib\site-packages (from scikit-learn) (1.26.4)

Requirement already satisfied: scipy>=1.6.0 in c:\users\lenovo\anaconda3\envs\karim-new\lib\site-packages (from scikit-learn) (1.12.0)

Requirement already satisfied: joblib>=1.2.0 in c:\users\lenovo\anaconda3\envs\karim-new\lib\site-packages (from scikit-learn) (1.4.2)

Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\lenovo\anaconda3\envs\karim-new\lib\site-packages (from scikit-learn) (3.5.0)

0

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import  VotingClassifier

In [3]:
cd D:\Courses\AI\Machine learning\My Courses\ML\My course\Day2

[WinError 3] The system cannot find the path specified: 'D:\\Courses\\AI\\Machine learning\\My Courses\\ML\\My course\\Day2'
d:\Web\AI Huawei Course\AI Day5


In [4]:
df=pd.read_csv("breast.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [5]:
Y=df["diagnosis"]
Y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [6]:
le = LabelEncoder()
Y=le.fit_transform(Y)

In [7]:
X=df.drop(["id", "diagnosis"], axis=1)
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [8]:
### Train Test Split of the data 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=45)

In [9]:
### Scaling the features X 
sc = RobustScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

#### Breast Cancer Classification using Logistic Regression

In [10]:
### Model Training 
LR = LogisticRegression(penalty='elasticnet' , l1_ratio=0.2, solver='saga')
LR.fit(X_train,y_train)

c:\Users\Lenovo\anaconda3\envs\Karim-new\lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(l1_ratio=0.2, penalty='elasticnet', solver='saga')

In [11]:
### Prediction of the classes by the model corresponding to the X_test
y_pred1= LR.predict(X_test)
print(classification_report(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       110
           1       1.00      0.97      0.98        61

    accuracy                           0.99       171
   macro avg       0.99      0.98      0.99       171
weighted avg       0.99      0.99      0.99       171

[[110   0]
 [  2  59]]


#### Breast Cancer Classification using KNN Classifier

In [12]:
knn=KNeighborsClassifier(n_neighbors=8)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=8)

In [13]:
y_pred2= knn.predict(X_test)
print(classification_report(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97       110
           1       0.98      0.92      0.95        61

    accuracy                           0.96       171
   macro avg       0.97      0.95      0.96       171
weighted avg       0.97      0.96      0.96       171

[[109   1]
 [  5  56]]


#### Breast Cancer classification using Decision Tree

In [14]:
dt= DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [15]:
y_pred3= dt.predict(X_test)
print(classification_report(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94       110
           1       0.91      0.87      0.89        61

    accuracy                           0.92       171
   macro avg       0.92      0.91      0.92       171
weighted avg       0.92      0.92      0.92       171

[[105   5]
 [  8  53]]


#### Breast Cancer Classification using SGD Classifier

In [16]:
sgd= SGDClassifier(loss="log_loss", alpha=0.0001, random_state=45)
sgd.fit(X_train,y_train)

SGDClassifier(loss='log_loss', random_state=45)

In [17]:
y_pred4= dt.predict(X_test)
print(classification_report(y_test, y_pred4))
print(confusion_matrix(y_test, y_pred4))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94       110
           1       0.91      0.87      0.89        61

    accuracy                           0.92       171
   macro avg       0.92      0.91      0.92       171
weighted avg       0.92      0.92      0.92       171

[[105   5]
 [  8  53]]


#### Breast Cancer Classification using Support vector machines with different kerenels

In [18]:
### Linear Kernel
sv =SVC(kernel='linear')
sv.fit(X_train,y_train)

SVC(kernel='linear')

In [19]:
y_pred5= sv.predict(X_test)
print(classification_report(y_test, y_pred5))
print(confusion_matrix(y_test, y_pred5))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       110
           1       1.00      0.95      0.97        61

    accuracy                           0.98       171
   macro avg       0.99      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171

[[110   0]
 [  3  58]]


#### Classification using Linear Discremenant analysis

In [20]:
lda=LinearDiscriminantAnalysis()
lda.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [21]:
y_pred6= knn.predict(X_test)
print(classification_report(y_test, y_pred6))
print(confusion_matrix(y_test, y_pred6))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97       110
           1       0.98      0.92      0.95        61

    accuracy                           0.96       171
   macro avg       0.97      0.95      0.96       171
weighted avg       0.97      0.96      0.96       171

[[109   1]
 [  5  56]]


#### Classification using naieve bayes

In [22]:
nb= GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [23]:
y_pred7=nb.predict(X_test)
print(classification_report(y_test, y_pred7))
print(confusion_matrix(y_test, y_pred7))

              precision    recall  f1-score   support

           0       0.93      0.98      0.96       110
           1       0.96      0.87      0.91        61

    accuracy                           0.94       171
   macro avg       0.95      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171

[[108   2]
 [  8  53]]


#### Creating  Ensemble voting classfier for breast cancer dataset

In [24]:
clf = VotingClassifier(estimators=[('lr', LR), ('svl', sv), ('lda', lda), ('sgd', sgd), ('nb', nb)], voting='hard')

In [25]:
clf.fit(X_train, y_train)

c:\Users\Lenovo\anaconda3\envs\Karim-new\lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


VotingClassifier(estimators=[('lr',
                              LogisticRegression(l1_ratio=0.2,
                                                 penalty='elasticnet',
                                                 solver='saga')),
                             ('svl', SVC(kernel='linear')),
                             ('lda', LinearDiscriminantAnalysis()),
                             ('sgd',
                              SGDClassifier(loss='log_loss', random_state=45)),
                             ('nb', GaussianNB())])

In [26]:
y_predensen= clf.predict(X_test)
print(classification_report(y_test, y_predensen))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       110
           1       1.00      0.95      0.97        61

    accuracy                           0.98       171
   macro avg       0.99      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171

